#! /bin/sh

#pgrep -x sxhkd > /dev/null || sxhkd &

#startup
sxhkd &
nm-applet &
$HOME/.config/polybar/start.sh &
picom --experimental-backends &
$HOME/scripts/monitors.sh &
nitrogen --restore &

#bspwm
bspc monitor DP-3 -d 1 2 3 4 
bspc monitor DVI-D-1 -d 5 6 7 8

bspc config border_width         5
bspc config window_gap          15

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a firefox desktop='^5'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


