#! /bin/sh

#pgrep -x sxhkd > /dev/null || sxhkd &

#startup
sxhkd &
nm-applet &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

#scripts
$HOME/.config/polybar/start.sh &
$HOME/scripts/monitors.sh &
$HOME/scripts/mouse.sh &
$HOME/scripts/centerwindow.sh &
$HOME/scripts/keyboard.sh &

picom --experimental-backends &
nitrogen --restore &

#bspwm
bspc monitor DP-0 -d 1 2 3 4 
bspc monitor DVI-D-0 -d 5 6 7 8

bspc config border_width         2
bspc config window_gap           0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle 	 true

bspc config focused_border_color \#61afef
bspc config normal_border_color \#1e222a
bspc config presel_feedback_color \#1e222a

bspc rule -a mplayer2 state=floating
bspc rule -a Shutter state=floating
bspc rule -a Pavucontrol state=floating
bspc rule -a vlc state=floating
bspc rule -a Nitrogen state=floating
